defmodule OskolWeb.GameArt.Sprite do
  @moduledoc false

  # Compile-time helper: turns a character grid into as few `<rect>`s as it
  # can. Equal neighbours merge along a row, then identical runs merge down
  # the rows, so a solid background costs one rect instead of a thousand.
  # It lives in its own module because `GameArt` calls it from a module
  # attribute, and a module cannot call itself while it is being defined.

  @doc "Rectangles covering every non-`.` cell of a character grid."
  def rects(rows, palette) do
    rows
    |> Enum.map(&runs(&1, palette))
    |> Enum.with_index()
    |> Enum.reduce({[], []}, &absorb_row/2)
    |> then(fn {closed, open} -> closed ++ open end)
  end

  defp runs(row, palette) do
    row
    |> String.graphemes()
    |> Enum.with_index()
    |> Enum.chunk_by(fn {char, _x} -> char end)
    |> Enum.reject(fn [{char, _} | _] -> char == "." end)
    |> Enum.map(fn chunk ->
      {char, x0} = List.first(chunk)
      {_, x1} = List.last(chunk)
      %{x: x0, w: x1 - x0 + 1, color: Map.get(palette, char, "#000")}
    end)
  end

  # A run directly under an open rect of the same span and colour extends it;
  # anything else opens a rect, and any open rect it did not extend is done.
  defp absorb_row({runs, y}, {closed, open}) do
    spans = MapSet.new(runs, &span/1)
    {extended, finished} = Enum.split_with(open, &MapSet.member?(spans, span(&1)))
    extended = Enum.map(extended, &%{&1 | h: &1.h + 1})
    kept = MapSet.new(extended, &span/1)

    fresh =
      for run <- runs, not MapSet.member?(kept, span(run)), do: Map.merge(run, %{y: y, h: 1})

    {finished ++ closed, extended ++ fresh}
  end

  defp span(%{x: x, w: w, color: color}), do: {x, w, color}
end

defmodule OskolWeb.GameArt do
  @moduledoc """
  Per-game presentation for the library: a notebook-palette accent and a
  small piece of pixel art drawn from a character grid. Presentation only;
  a game with no entry here gets a neutral accent and a generic sprite, so
  registering a game never requires touching this module.

  A game's art is a list of frames. They are stacked into a reel and cycled
  by one CSS `steps()` animation on a single transform — no JavaScript, no
  LiveView ticks, nothing to schedule on a phone. `prefers-reduced-motion`
  drops the animation, which leaves the first frame showing.
  """
  use Phoenix.Component

  alias OskolWeb.GameArt.Sprite

  # How long one frame of a game's art is held.
  @frame_ms 800

  # Notebook palette: pen blue, red pen, highlighter, pencil, marker colours.
  @palette %{
    "W" => "#ffffff",
    "K" => "#23243a",
    "L" => "#3d3f5c",
    "R" => "#e3453b",
    "B" => "#2f5fd0",
    "Y" => "#ffd93d",
    "G" => "#62c370",
    "P" => "#f27ba1",
    "S" => "#6ec1ff",
    "T" => "#f1dcb3",
    "N" => "#b97a4f",
    "E" => "#43286e",
    "M" => "#7d4fc9",
    "C" => "#e8f1f7",
    "A" => "#3fa7d6",
    "Z" => "#1a5a7d",
    "D" => "#8fcbe8",
    "X" => "#7a4a28"
  }

  @accents %{
    "poker" => "#7d4fc9",
    "backgammon" => "#3fa7d6",
    "chess" => "#3d3f5c",
    "go" => "#b97a4f"
  }

  # Each game is a storyboard: the frames loop, so the last frame reads as
  # the moment before the first.
  @sprites %{
    "poker" => [
      ~w(
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
      ),
      ~w(
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEKKKKKEKKKKKEKKKKKEEEEEEEEEEEEEEM
        MEKWWWKEKWWWKEKWWWKEEEEEEEEEEEEEEM
        MEKWRWKEKWKWKEKWRWKEEEEEEEEEEEEEEM
        MEKRRRKEKKKKKEKRRRKEEEEEEEEEEEEEEM
        MEKWRWKEKWKWKEKWRWKEEEEEEEEEEEEEEM
        MEKWWWKEKWWWKEKWWWKEEEEEEEEEEEEEEM
        MEKKKKKEKKKKKEKKKKKEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM
        MEEEEEEEEEEKRRRKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
      ),
      ~w(
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEKKKKKEKKKKKEKKKKKEKKKKKEEEEEEEEM
        MEKWWWKEKWWWKEKWWWKEKWWWKEEEEEEEEM
        MEKWRWKEKWKWKEKWRWKEKWKWKEEEEEEEEM
        MEKRRRKEKKKKKEKRRRKEKKKKKEEEEEEEEM
        MEKWRWKEKWKWKEKWRWKEKWKWKEEEEEEEEM
        MEKWWWKEKWWWKEKWWWKEKWWWKEEEEEEEEM
        MEKKKKKEKKKKKEKKKKKEKKKKKEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM
        MEEEEEEEEEEKRRRKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
      ),
      ~w(
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM
        MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM
        MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM
        MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM
        MEKRRRKEKKKKKEKRRRKEKKKKKEKRRRKEEM
        MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM
        MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM
        MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM
        MEEEEEEEEEEKRRRKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
      ),
      ~w(
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKWKWKEKWRWKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKRRRKEEEEEEEEEEEM
        MEEEEEEEEEEKWKWKEKWRWKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM
        MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM
        MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM
        MEKRRRKEKKKKKEKRRRKEKKKKKEKRRRKEEM
        MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM
        MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM
        MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM
        MEEEEEEEEEEKRRRKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
      ),
      ~w(
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKWKWKEKWRWKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKRRRKEEEEEEEEEEEM
        MEEEEEEEEEEKWKWKEKWRWKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM
        MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM
        MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM
        MEKRRRKEKKKKKEKRRRKEKKKKKEKRRRKEEM
        MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM
        MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM
        MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM
        MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM
        MEEEEEEEEEEKRRRKEKKKKKEEEYYYYYEEEM
        MEEEEEEEEEEKWRWKEKWKWKEEERRRRREEEM
        MEEEEEEEEEEKWWWKEKWWWKEEEYYYYYEEEM
        MEEEEEEEEEEKKKKKEKKKKKEEERRRRREEEM
        MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
      )
    ],
    "backgammon" => [
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KAKKKADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK
        KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK
        KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK
        KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK
        KAKKKADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK
        KAKKKADDDDDAAAAADDDDDAKKKADDDDDKCCCCCCCK
        KKWWWKDDDDDAAAAADDDDDKZZZKDDDDDKCCCCCCCK
        KKWWWKDDDDDAAAAADDDDDKZZZKDDDDDKCCCCCCCK
        KKWWWKDDDDDAAAAADDDDDKZZZKDDDDDKCCCCCCCK
        KCKKKCCDDDCCAAACCDDDCCKKKCCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KAKKKADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK
        KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK
        KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK
        KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK
        KAKKKADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCKKKCCKKKCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KAAAAADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCKKKCCKKKCKCCKKKCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCKKKCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK
        KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KAAAAADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCKKKCCKKKCKCCKKKCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCKKKCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK
        KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KAAAAADDDDDAKKKADKKKDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAKKKADKKKDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCKKKCCKKKCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK
        KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KAAAAADDDDDAKKKADKKKDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK
        KAAAAADDDDDAKKKADKKKDAKKKADKKKDKCCCCCCCK
        KAAAAADDDDDAAAAADKKKDAAAAADKKKDKCCCCCCCK
        KAAAAADDDDDAAAAAKZZZKAAAAAKWWWKKCCCCCCCK
        KAAAAADDDDDAAAAAKZZZKAAAAAKWWWKKCCCCCCCK
        KAAAAADDDDDAAAAAKZZZKAAAAAKWWWKKCCCCCCCK
        KCAAACCDDDCCAAACCKKKCCAAACCKKKCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK
        KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK
        KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK
        KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      )
    ],
    "chess" => [
      ~w(
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        LTLTNLLNTLTTLLLNTLTTNLNNTLLTLNLN
        LLLTLLLNLLLTNLNNLLLTLLLNLLLTLLLN
        LLLTLNLNTLTTLLLNLLLTNLNNLTLTLLLN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NLNNTLTTNLNNTLTTNLNNTLTTNLNNTLTT
        LLLNLLLTLLLNLLLTLLLNLLLTLLLNLLLT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TWTTNWNNTWTTNWNNTWTTNWNNTWTTNWNN
        WWWTWWWNWWWTWWWNWWWTWWWNWWWTWWWN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        WNWNTWWTNWNNWWWTNWNNTWTTNWWNWTWT
        WWWNWWWTWWWNTWTTWWWNWWWTWWWNWWWT
        WWWNWTWTNWNNWWWTWWWNTWTTWNWNWWWT
      ),
      ~w(
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        LTLTNLLNTLTTLLLNTLTTNLNNTLLTLNLN
        LLLTLLLNLLLTNLNNLLLTLLLNLLLTLLLN
        LLLTLNLNTLTTLLLNLLLTNLNNLTLTLLLN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NLNNTLTTNLNNTLTTNLNNTLTTNLNNTLTT
        LLLNLLLTLLLNLLLTLLLNLLLTLLLNLLLT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTWTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNWWWTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TWTTNWNNTWTTNWNNTTTTNWNNTWTTNWNN
        WWWTWWWNWWWTWWWNTTTTWWWNWWWTWWWN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        WNWNTWWTNWNNWWWTNWNNTWTTNWWNWTWT
        WWWNWWWTWWWNTWTTWWWNWWWTWWWNWWWT
        WWWNWTWTNWNNWWWTWWWNTWTTWNWNWWWT
      ),
      ~w(
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        LTLTNLLNTLTTLLLNTLTTNLNNTLLTLNLN
        LLLTLLLNLLLTNLNNLLLTLLLNLLLTLLLN
        LLLTLNLNTLTTLLLNLLLTNLNNLTLTLLLN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NLNNTLTTNLNNTLTTNNNNTLTTNLNNTLTT
        LLLNLLLTLLLNLLLTNNNNLLLTLLLNLLLT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNLNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTLLLNTTTTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTWTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNWWWTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TWTTNWNNTWTTNWNNTTTTNWNNTWTTNWNN
        WWWTWWWNWWWTWWWNTTTTWWWNWWWTWWWN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        WNWNTWWTNWNNWWWTNWNNTWTTNWWNWTWT
        WWWNWWWTWWWNTWTTWWWNWWWTWWWNWWWT
        WWWNWTWTNWNNWWWTWWWNTWTTWNWNWWWT
      ),
      ~w(
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        LTLTNLLNTLTTLLLNTLTTNLNNTLLTLNLN
        LLLTLLLNLLLTNLNNLLLTLLLNLLLTLLLN
        LLLTLNLNTLTTLLLNLLLTNLNNLTLTLLLN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NLNNTLTTNLNNTLTTNNNNTLTTNLNNTLTT
        LLLNLLLTLLLNLLLTNNNNLLLTLLLNLLLT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNLNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTLLLNTTTTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTWTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNWWWTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTWWTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNWWWTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNWTWTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TWTTNWNNTWTTNWNNTTTTNWNNTWTTNWNN
        WWWTWWWNWWWTWWWNTTTTWWWNWWWTWWWN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        WNWNTWWTNWNNWWWTNWNNTWTTNNNNWTWT
        WWWNWWWTWWWNTWTTWWWNWWWTNNNNWWWT
        WWWNWTWTNWNNWWWTWWWNTWTTNNNNWWWT
      ),
      ~w(
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        LTLTNNNNTLTTLLLNTLTTNLNNTLLTLNLN
        LLLTNNNNLLLTNLNNLLLTLLLNLLLTLLLN
        LLLTNNNNTLTTLLLNLLLTNLNNLTLTLLLN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NLNNTLTTNLNNTLTTNNNNTLTTNLNNTLTT
        LLLNLLLTLLLNLLLTNNNNLLLTLLLNLLLT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTLLTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNLLLTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNLTLTNNNNTTTTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNLNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTLLLNTTTTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTWTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNWWWTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTWWTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNWWWTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNWTWTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TWTTNWNNTWTTNWNNTTTTNWNNTWTTNWNN
        WWWTWWWNWWWTWWWNTTTTWWWNWWWTWWWN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        WNWNTWWTNWNNWWWTNWNNTWTTNNNNWTWT
        WWWNWWWTWWWNTWTTWWWNWWWTNNNNWWWT
        WWWNWTWTNWNNWWWTWWWNTWTTNNNNWWWT
      ),
      ~w(
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        LTLTNNNNTLTTLLLNTLTTNLNNTLLTLNLN
        LLLTNNNNLLLTNLNNLLLTLLLNLLLTLLLN
        LLLTNNNNTLTTLLLNLLLTNLNNLTLTLLLN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NLNNTLTTNLNNTLTTNNNNTLTTNLNNTLTT
        LLLNLLLTLLLNLLLTNNNNLLLTLLLNLLLT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTLLTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNLLLTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNLTLTNNNNTTTTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNLNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTLLLNTTTTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTWTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNWWWTNNNNTWTTNNNNTTTTNNNN
        TTTTNNNNTWTTNNNNWWWTNNNNTTTTNNNN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNTWWTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNWWWTNNNNTTTT
        NNNNTTTTNNNNTTTTNNNNWTWTNNNNTTTT
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN
        TWTTNWNNTWTTNWNNTTTTNWNNTWTTNWNN
        WWWTWWWNWWWTWWWNTTTTWWWNWWWTWWWN
        NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT
        WNWNTWWTNWNNWWWTNWNNTTTTNNNNWTWT
        WWWNWWWTWWWNTWTTWWWNTTTTNNNNWWWT
        WWWNWTWTNWNNWWWTWWWNTTTTNNNNWWWT
      )
    ],
    "go" => [
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNKKKNXNNXNNXNNXNNXNK
        KNNXXXXXXXXKKKXXXXXXXXXXXXXXNK
        KNNXNNXNNXNKKKNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK
        KNNXXXXXXXXKKKWWWXXXXXXXXXXXNK
        KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK
        KNNXXXXXXXXKKKWWWXXXXXXXXXXXNK
        KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK
        KNNXXXXXXXXKKKWWWXXXXXXXXXXXNK
        KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXNNXNNXNKKKWWWKKKNXNNXNNXNK
        KNNXXXXXXXXKKKWWWKKKXXXXXXXXNK
        KNNXNNXNNXNKKKWWWKKKNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXNNXNNXNKKKWWWKKKNXNNXNNXNK
        KNNXXXXXXXXKKKWWWKKKXXXXXXXXNK
        KNNXNNXNNXNKKKWWWKKKNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXNNXNNXNKKKNXNKKKNXNNXNNXNK
        KNNXXXXXXXXKKKXXXKKKXXXXXXXXNK
        KNNXNNXNNXNKKKNXNKKKNXNNXNNXNK
        KNNXNNXNNXNNXNKKKNXNWWWNXNNXNK
        KNNXXXXXXXXXXXKKKXXXWWWXXXXXNK
        KNNXNNXNNXNNXNKKKNXNWWWNXNNXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      ),
      ~w(
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNWWWNXNNXNNXNNXNNXNNXNK
        KNNXXXXXWWWXXXXXXXXXXXXXXXXXNK
        KNNXNNXNWWWNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK
        KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK
        KNNXNNXNNXNKKKNXNKKKNXNNXNNXNK
        KNNXXXXXXXXKKKXXXKKKXXXXXXXXNK
        KNNXNNXNNXNKKKNXNKKKNXNNXNNXNK
        KNNXNNXNNXNNXNKKKNXNWWWNXNNXNK
        KNNXXXXXXXXXXXKKKXXXWWWXXXXXNK
        KNNXNNXNNXNNXNKKKNXNWWWNXNNXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK
        KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK
        KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK
        KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK
        KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      )
    ],
    "default" => [
      ~w(
        ........................
        ....KKKKKK..............
        ...KWWWWWWK.............
        ...KWKWWKWK...KKKKKK....
        ...KWWWWWWK..KSSSSSSK...
        ...KWWKKWWK..KSKSSKSK...
        ...KWWWWWWK..KSSSSSSK...
        ....KKKKKK...KSKSSKSK...
        .............KSSSSSSK...
        ..............KKKKKK....
        ........................
        ......YYYYYYYYYY........
        ......YKKKKKKKKY........
        ......YYYYYYYYYY........
        ........................
        ........................
      )
    ]
  }

  # Decomposed once, at compile time.
  @frames Map.new(@sprites, fn {slug, frames} ->
            {slug,
             Enum.map(frames, fn rows ->
               %{
                 w: rows |> List.first() |> String.length(),
                 h: length(rows),
                 rects: Sprite.rects(rows, @palette)
               }
             end)}
          end)

  @doc "Accent colour for a game slug."
  def accent(slug), do: Map.get(@accents, slug, "#6b6b78")

  @doc "Number of frames in a game's art. For tests."
  def frame_count(slug), do: length(Map.get(@frames, slug, @frames["default"]))

  attr :slug, :string, required: true
  attr :class, :string, default: ""
  attr :animate, :boolean, default: true

  @doc """
  Pixel art for the game as crisp SVG rectangles. With `animate` the frames
  are stacked into a reel that a single keyframe animation steps through;
  without it only the first frame is rendered.
  """
  def art(assigns) do
    frames = Map.get(@frames, assigns.slug, @frames["default"])
    first = List.first(frames)
    frames = if assigns.animate, do: frames, else: [first]

    assigns =
      assign(assigns,
        frames: frames,
        count: length(frames),
        width: first.w,
        height: first.h,
        duration: length(frames) * @frame_ms
      )

    ~H"""
    <div
      class={["game-art", @count > 1 && "game-art-anim", @class]}
      style={"aspect-ratio: #{@width} / #{@height}; --art-frames: #{@count}; --art-duration: #{@duration}ms"}
      aria-hidden="true"
    >
      <div class="game-art-reel">
        <svg
          :for={frame <- @frames}
          viewBox={"0 0 #{@width} #{@height}"}
          shape-rendering="crispEdges"
        >
          <rect
            :for={r <- frame.rects}
            x={r.x}
            y={r.y}
            width={r.w}
            height={r.h}
            fill={r.color}
          />
        </svg>
      </div>
    </div>
    """
  end
end
