defmodule Mix.Tasks.Oskol.Fixtures do
  @shortdoc "Regenerate the seeded playout fixtures shared by the Gleam and Elm test suites"
  @moduledoc """
  Runs seeded random playouts for every registered game through the Gleam
  fixture generator and writes two corpora:

    * `test/fixtures/replays/<game>-<format>-<seed>.json`: the action log and
      the final scene fingerprint of a full playout. Small, one per format
      and seed. Gleam golden tests replay them; a changed fingerprint means
      the rules changed.
    * `test/fixtures/payloads/<game>-<format>-<seed>.json`: the first steps of
      a playout with every update every viewer would have received, also
      embedded in `assets/tests/Fixtures.elm` for elm-test. A changed shape
      means the clients must follow.

  The replays are committed and guarded by `test/gamekit/golden_test.gleam`.
  The payloads and `Fixtures.elm` are derived (and large), so they are not
  committed: `bin/check` and CI generate them before running elm-test.

      mix oskol.fixtures            # everything
      mix oskol.fixtures replays    # only the committed golden replays
      mix oskol.fixtures payloads   # only the payload corpus + Fixtures.elm

  Regenerate the replays after changing rules or the wire protocol on
  purpose, then read the diff.
  """
  use Mix.Task

  @replay_seeds 1..3
  @replay_max_steps 4000
  @payload_seeds 1..1
  @payload_steps 40

  @impl true
  def run(args) do
    Mix.Task.run("app.config")
    File.mkdir_p!("test/fixtures/replays")
    File.mkdir_p!("test/fixtures/payloads")
    seats = [{"p1", "Alice"}, {"p2", "Bob"}]

    what =
      case args do
        ["replays"] -> :replays
        ["payloads"] -> :payloads
        [] -> :all
        other -> Mix.raise("Unknown argument #{inspect(other)}: use replays, payloads or nothing")
      end

    if what in [:all, :replays], do: replays(seats)
    if what in [:all, :payloads], do: payloads(seats)
  end

  defp replays(seats) do
    for game <- Oskol.GameKit.games(), format <- game["formats"], seed <- @replay_seeds do
      name = "#{game["slug"]}-#{format["id"]}-#{seed}"

      case :gamekit@host.replay_json(game["slug"], format["id"], seats, seed, @replay_max_steps) do
        {:ok, json} ->
          File.write!("test/fixtures/replays/#{name}.json", json)
          steps = json |> Jason.decode!() |> Map.get("steps") |> length()
          Mix.shell().info("replay  #{name}: #{steps} steps")

        {:error, reason} ->
          Mix.raise("replay #{name}: #{reason}")
      end
    end
  end

  defp payloads(seats) do
    payloads =
      for game <- Oskol.GameKit.games(), format <- game["formats"], seed <- @payload_seeds do
        name = "#{game["slug"]}-#{format["id"]}-#{seed}"

        case :gamekit@host.fixture_json(game["slug"], format["id"], seats, seed, @payload_steps) do
          {:ok, json} ->
            File.write!("test/fixtures/payloads/#{name}.json", json)
            Mix.shell().info("payload #{name}: #{byte_size(json)} bytes")
            {name, json}

          {:error, reason} ->
            Mix.raise("payload #{name}: #{reason}")
        end
      end

    File.write!("assets/tests/Fixtures.elm", elm_module(payloads))
    Mix.shell().info("wrote assets/tests/Fixtures.elm (#{length(payloads)} fixtures)")
    puzzles()
  end

  # The puzzle wire is frozen and the Elm side decodes it strictly, so the
  # Elm suite is handed the server's own bytes rather than a copy of them.
  # Pure: `samples/0` needs no repo and no capabilities.
  defp puzzles do
    samples = Enum.map(:oskol@puzzles@fixture.samples(), fn {name, json} -> {name, json} end)

    File.write!(
      "assets/tests/PuzzleApiFixtures.elm",
      elm_module(samples, "PuzzleApiFixtures", puzzle_doc())
    )

    Mix.shell().info("wrote assets/tests/PuzzleApiFixtures.elm (#{length(samples)} puzzles)")
  end

  defp puzzle_doc do
    """
    Each entry is one `GET /papi/puzzles/:id` answer, rendered by
    `oskol/handlers/puzzles` itself: the question, the legal-move tree and
    the prompt, for a checker play, a doubles roll, a double and a take.
    """
  end

  defp elm_module(fixtures, module \\ "Fixtures", doc \\ nil) do
    entries =
      Enum.map_join(fixtures, "\n    , ", fn {name, json} ->
        ~s|( "#{name}", #{elm_string(json)} )|
      end)

    doc =
      doc ||
        """
        Each entry is the start of a seeded playout as produced by gamekit/fixture:
        every update payload every viewer would have received, step by step.
        """

    """
    module #{module} exposing (all)

    {-| GENERATED by `mix oskol.fixtures`. Do not edit.

    #{String.trim_trailing(doc)}

    -}


    all : List ( String, String )
    all =
        [ #{entries}
        ]
    """
  end

  defp elm_string(text) do
    escaped =
      text
      |> String.replace("\\", "\\\\")
      |> String.replace("\"", "\\\"")

    "\"" <> escaped <> "\""
  end
end
