module FixtureLoader exposing (Fixture, Step, Viewer, all, byGame, decode)

{-| Decodes the payload fixtures generated by `mix oskol.fixtures` into the
protocol types the client uses, so every test starts from what the server
actually sends.
-}

import Dict exposing (Dict)
import Fixtures
import Json.Decode as D
import Protocol exposing (Update)


type alias Viewer =
    { id : String, update : Update }


type alias Step =
    { playerId : String
    , action : String
    , updates : Dict String Update
    }


type alias Fixture =
    { name : String
    , game : String
    , format : String
    , seed : Int
    , seats : List ( String, String )
    , finished : Bool
    , initial : Dict String Update
    , steps : List Step
    }


decode : ( String, String ) -> Result D.Error Fixture
decode ( name, json ) =
    D.decodeString (fixtureDecoder name) json


fixtureDecoder : String -> D.Decoder Fixture
fixtureDecoder name =
    D.map7 (Fixture name)
        (D.field "game" D.string)
        (D.field "format" D.string)
        (D.field "seed" D.int)
        (D.field "seats" (D.list (D.map2 Tuple.pair (D.field "id" D.string) (D.field "name" D.string))))
        (D.field "finished" D.bool)
        (D.field "initial" (D.dict Protocol.updateDecoder))
        (D.field "steps" (D.list stepDecoder))


stepDecoder : D.Decoder Step
stepDecoder =
    D.map3 Step
        (D.field "player_id" D.string)
        (D.field "action" D.string)
        (D.field "updates" (D.dict Protocol.updateDecoder))


{-| Every fixture, decoded. A decode failure is itself a test failure
elsewhere; here it is simply dropped.
-}
all : List Fixture
all =
    Fixtures.all |> List.filterMap (decode >> Result.toMaybe)


byGame : String -> List Fixture
byGame slug =
    List.filter (\f -> f.game == slug) all
