module PuzzlePageTest exposing (suite)

{-| The puzzle page on the server's own answers: `PuzzleApiFixtures` (the
question) and `PuzzleRevealFixtures` (what an attempt is answered with,
and the schedule shapes), both generated by `mix oskol.fixtures` straight
out of `oskol/handlers/puzzles`.

What is asserted is the client's side of the contract: the reveal decodes,
a tap walks the board and PLAY posts exactly the path walked with the
page's key, the verdict and the move played are shown, the cube scale
marks the engine's band, the level line reads each schedule right, NEXT
follows the shell, and the memory line appears on a 200 and never on a
404.

-}

import Api
import Api.Practice as Practice
import Dict
import Expect
import Games.Backgammon.Puzzle as Puzzle exposing (Verdict(..))
import Html
import Html.Attributes
import Json.Decode as D
import Json.Encode as E
import Page.Puzzle as Page exposing (Attempt(..), Msg(..))
import PuzzleApiFixtures
import PuzzleRevealFixtures
import Session
import Test exposing (Test, describe, test)
import Test.Html.Query as Query
import Test.Html.Selector exposing (attribute, class, id, tag, text)
import Ui.SignIn as SignIn


suite : Test
suite =
    describe "the puzzle page"
        [ decoding
        , staging
        , posting
        , revealing
        , cube
        , schedule
        , next
        , runEnd
        , memory
        , sharing
        , story
        ]



-- FIXTURES


fixture : List ( String, String ) -> String -> String
fixture all name =
    all |> List.filter (\( n, _ ) -> n == name) |> List.head |> Maybe.map Tuple.second |> Maybe.withDefault ""


question : String -> String
question =
    fixture PuzzleApiFixtures.all


reveal : String -> String
reveal =
    fixture PuzzleRevealFixtures.all


{-| A reveal with a schedule spliced in where the guest's `null` was: what
the same endpoint answers an account.
-}
revealWith : String -> String -> String
revealWith name scheduleName =
    String.replace "\"schedule\":null" ("\"schedule\":" ++ reveal scheduleName) (reveal name)


decodeReveal : String -> Result String Puzzle.Reveal
decodeReveal body =
    Api.parseBody Puzzle.revealDecoder body |> Result.mapError Api.errorMessage


{-| A page with the question in and the key minted.
-}
page : { hasNext : Bool } -> String -> Page.Model
page config name =
    let
        ( model, _ ) =
            Page.init Session.empty { id = "fix", hasNext = config.hasNext, origin = "http://oskol.test", share = Nothing }

        loaded =
            case D.decodeString Puzzle.decoder (question name) of
                Ok p ->
                    GotPuzzle (Ok p)

                Err e ->
                    GotPuzzle (Err (Api.DecodeError (D.errorToString e)))
    in
    model |> step loaded |> step (GotKey "key-0123")


step : Msg -> Page.Model -> Page.Model
step msg model =
    let
        ( next_, _, _ ) =
            Page.update msg model
    in
    next_


out : Msg -> Page.Model -> Page.Out
out msg model =
    let
        ( _, _, o ) =
            Page.update msg model
    in
    o


revealed : String -> Page.Model -> Page.Model
revealed body model =
    case decodeReveal body of
        Ok r ->
            step (GotReveal (Ok r)) model

        Err e ->
            step (GotReveal (Err (Api.DecodeError e))) model


rendered : Page.Model -> Query.Single Msg
rendered model =
    Page.view model |> Query.fromHtml


{-| The tree of the page's question, and a path root -> terminal through
it: the first complete turn the tree offers, as a tap sequence.
-}
aTurn : Page.Model -> ( List String, List Puzzle.Child )
aTurn model =
    case model.puzzle of
        Page.Loaded p ->
            case p.tree of
                Just tree ->
                    let
                        walk id path steps =
                            case Dict.get id tree.nodes of
                                Just node ->
                                    case node.children of
                                        [] ->
                                            ( List.reverse path, List.reverse steps )

                                        child :: _ ->
                                            walk child.node (child.node :: path) (child :: steps)

                                Nothing ->
                                    ( List.reverse path, List.reverse steps )
                    in
                    walk tree.root [] []

                Nothing ->
                    ( [], [] )

        _ ->
            ( [], [] )


has : List Test.Html.Selector.Selector -> Query.Single msg -> Expect.Expectation
has selectors q =
    q |> Query.findAll selectors |> Query.count (Expect.atLeast 1)


hasNot : List Test.Html.Selector.Selector -> Query.Single msg -> Expect.Expectation
hasNot selectors q =
    q |> Query.findAll selectors |> Query.count (Expect.equal 0)



-- DECODING


decoding : Test
decoding =
    describe "every reveal the server sends decodes"
        ((PuzzleRevealFixtures.all
            |> List.filter (\( name, _ ) -> not (String.startsWith "schedule" name))
            |> List.map
                (\( name, body ) ->
                    test name <|
                        \_ ->
                            case decodeReveal body of
                                Ok r ->
                                    Expect.all
                                        [ \_ -> Puzzle.verdictName r.verdict |> Expect.equal (String.split "_" name |> List.drop 1 |> String.join "_")
                                        , \_ ->
                                            -- the answer is either a play or a cube, never both, never neither
                                            (r.best /= Nothing) |> Expect.notEqual (r.cube /= Nothing)
                                        , \_ -> r.schedule |> Expect.equal Nothing
                                        ]
                                        ()

                                Err e ->
                                    Expect.fail e
                )
         )
            ++ [ test "every schedule shape decodes" <|
                    \_ ->
                        [ "schedule_amendable", "schedule_self_grade", "schedule_settled" ]
                            |> List.map (\n -> D.decodeString Puzzle.scheduleDecoder (reveal n) |> Result.map (\s -> ( s.amendable, s.selfGrade )))
                            |> Expect.equal [ Ok ( True, False ), Ok ( False, True ), Ok ( False, False ) ]
               , test "a verdict the page does not know fails the answer rather than becoming unknown" <|
                    \_ ->
                        decodeReveal (String.replace "\"verdict\":\"pass\"" "\"verdict\":\"meh\"" (reveal "move_pass"))
                            |> Expect.err
               ]
        )



-- STAGING


staging : Test
staging =
    describe "a move staged via the board"
        [ test "the question renders the board and asks in the server's words" <|
            \_ ->
                rendered (page { hasNext = False } "move")
                    |> Expect.all
                        [ has [ id "pz-board" ]
                        , \q -> q |> Query.find [ id "pz-prompt" ] |> Query.has [ text "White to play 6-4. What's your play?" ]
                        , \q -> q |> Query.find [ id "pz-score" ] |> Query.has [ text "White 3 away, Black 5 away · cube centred" ]
                        , hasNot [ id "pz-reveal" ]
                        , hasNot [ id "pz-share" ]
                        ]
        , test "one point each way is a single game; marked Crawford it is a match; no score is unlimited" <|
            \_ ->
                let
                    scored mover opp crawford =
                        question "move"
                            |> String.replace "\"mover_away\":3,\"opponent_away\":5" ("\"mover_away\":" ++ mover ++ ",\"opponent_away\":" ++ opp)
                            |> String.replace "\"crawford\":false" ("\"crawford\":" ++ crawford)

                    scoreLineOf json =
                        case D.decodeString Puzzle.decoder json of
                            Ok p ->
                                let
                                    ( fresh, _ ) =
                                        Page.init Session.empty { id = "fix", hasNext = False, origin = "", share = Nothing }
                                in
                                rendered (step (GotPuzzle (Ok p)) fresh) |> Query.find [ id "pz-score" ]

                            Err e ->
                                Query.fromHtml (Html.text (D.errorToString e))
                in
                Expect.all
                    [ \_ -> scoreLineOf (scored "1" "1" "false") |> Query.has [ text "Single game · cube centred" ]
                    , \_ -> scoreLineOf (scored "1" "1" "true") |> Query.has [ text "White 1 away, Black 1 away · Crawford · cube centred" ]
                    , \_ -> scoreLineOf (String.replace "\"score\":{\"mover_away\":3,\"opponent_away\":5}" "\"score\":null" (question "move")) |> Query.has [ text "Unlimited · cube centred" ]
                    ]
                    ()
        , test "a tap walks to a child and UNDO walks back" <|
            \_ ->
                let
                    model =
                        page { hasNext = False } "move"

                    ( path, _ ) =
                        aTurn model

                    first =
                        List.take 1 path

                    stepped =
                        step (BoardOut (Puzzle.Stepped first)) model
                in
                Expect.all
                    [ \_ -> stepped.path |> Expect.equal first
                    , \_ -> rendered stepped |> has [ id "bg-action-undo" ]
                    , \_ -> (step (BoardOut Puzzle.Undo) stepped).path |> Expect.equal []
                    ]
                    ()
        , test "a step to a node a lazy tree does not hold yet is fetched, and lands in the tree" <|
            \_ ->
                let
                    model =
                        page { hasNext = False } "move"

                    ( path, _ ) =
                        aTurn model

                    lazy =
                        { model
                            | puzzle =
                                case model.puzzle of
                                    Page.Loaded p ->
                                        Page.Loaded
                                            { p
                                                | tree =
                                                    p.tree
                                                        |> Maybe.map
                                                            (\t ->
                                                                { t
                                                                    | lazy = True
                                                                    , nodes = List.foldl Dict.remove t.nodes path
                                                                }
                                                            )
                                            }

                                    other ->
                                        other
                        }

                    first =
                        List.head path |> Maybe.withDefault ""

                    node =
                        case model.puzzle of
                            Page.Loaded p ->
                                p.tree |> Maybe.andThen (\t -> Dict.get first t.nodes)

                            _ ->
                                Nothing

                    stepped =
                        step (BoardOut (Puzzle.Stepped [ first ])) lazy

                    landed =
                        case node of
                            Just n ->
                                step (GotNode first (Ok n)) stepped

                            Nothing ->
                                stepped
                in
                Expect.all
                    [ \_ -> stepped.fetching |> Expect.equal [ first ]
                    , \_ -> stepped.path |> Expect.equal [ first ]
                    , \_ -> landed.fetching |> Expect.equal []
                    , \_ ->
                        (case landed.puzzle of
                            Page.Loaded p ->
                                p.tree |> Maybe.map (\t -> Dict.member first t.nodes)

                            _ ->
                                Nothing
                        )
                            |> Expect.equal (Just True)
                    ]
                    ()
        ]



-- POSTING


posting : Test
posting =
    describe "PLAY posts the right body"
        [ test "the moves of the path walked, in order, with the page's key" <|
            \_ ->
                let
                    model =
                        page { hasNext = False } "move"

                    ( path, steps ) =
                        aTurn model

                    walked =
                        step (BoardOut (Puzzle.Stepped path)) model

                    expected =
                        E.object
                            [ ( "moves"
                              , E.list (\c -> E.object [ ( "from", E.string c.from ), ( "to", E.string c.to ), ( "die", E.int c.die ) ]) steps
                              )
                            , ( "key", E.string "key-0123" )
                            ]
                in
                Expect.all
                    [ \_ -> List.length steps |> Expect.atLeast 1
                    , \_ -> Page.attemptBody walked |> Maybe.map (E.encode 0) |> Expect.equal (Just (E.encode 0 expected))
                    , \_ -> (step (BoardOut Puzzle.Play) walked).attempt |> Expect.equal Sending
                    ]
                    ()
        , test "half a turn is not an attempt" <|
            \_ ->
                let
                    model =
                        page { hasNext = False } "move"

                    ( path, _ ) =
                        aTurn model

                    half =
                        step (BoardOut (Puzzle.Stepped (List.take 1 path))) model
                in
                Expect.all
                    [ \_ -> List.length path |> Expect.atLeast 2
                    , \_ -> Page.attemptBody half |> Expect.equal Nothing
                    , \_ -> (step (BoardOut Puzzle.Play) half).attempt |> Expect.equal NotYet
                    ]
                    ()
        , test "PLAY before the key is minted waits for it, then goes" <|
            \_ ->
                let
                    ( fresh, _ ) =
                        Page.init Session.empty { id = "fix", hasNext = False, origin = "", share = Nothing }

                    model =
                        case D.decodeString Puzzle.decoder (question "move") of
                            Ok p ->
                                step (GotPuzzle (Ok p)) fresh

                            Err _ ->
                                fresh

                    ( path, _ ) =
                        aTurn model

                    pressed =
                        model |> step (BoardOut (Puzzle.Stepped path)) |> step (BoardOut Puzzle.Play)
                in
                Expect.all
                    [ \_ -> pressed.attempt |> Expect.equal NotYet
                    , \_ -> pressed.playWhenKeyed |> Expect.equal True
                    , \_ -> (step (GotKey "k") pressed).attempt |> Expect.equal Sending
                    ]
                    ()
        , test "a refused attempt is a sentence, and the board stays" <|
            \_ ->
                let
                    model =
                        page { hasNext = False } "move"

                    ( path, _ ) =
                        aTurn model

                    refused =
                        model
                            |> step (BoardOut (Puzzle.Stepped path))
                            |> step (GotReveal (Err (Api.ApiError { code = "validation_failed", message = "That is not a legal way to play the roll" })))
                in
                Expect.all
                    [ \_ -> refused.attempt |> Expect.equal (Refused "That is not a legal way to play the roll")
                    , \_ -> rendered refused |> Query.find [ id "pz-refused" ] |> Query.has [ text "That is not a legal way to play the roll" ]
                    , \_ -> rendered refused |> has [ id "bg-action-play" ]
                    , \_ -> (step (BoardOut Puzzle.Undo) refused).path |> Expect.equal (List.take (List.length path - 1) path)
                    ]
                    ()
        ]



-- THE REVEAL


revealing : Test
revealing =
    let
        after name =
            let
                model =
                    page { hasNext = False } "move"

                ( path, _ ) =
                    aTurn model
            in
            model |> step (BoardOut (Puzzle.Stepped path)) |> revealed (reveal name)
    in
    describe "the reveal"
        [ test "a hold: the verdict, the words, the candidates with yours marked" <|
            \_ ->
                rendered (after "move_hold")
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-verdict" ] |> Query.has [ attribute (Html.Attributes.attribute "data-verdict" "hold"), text "CLOSE" ]
                        , \q -> q |> Query.find [ id "pz-reveal" ] |> Query.has [ text "You played a dubious move." ]
                        , \q -> q |> Query.findAll [ class "rp-cand" ] |> Query.count (Expect.equal 3)
                        , \q -> q |> Query.findAll [ class "rp-cand", attribute (Html.Attributes.attribute "data-yours" "true") ] |> Query.count (Expect.equal 1)
                        , \q -> q |> Query.find [ class "rp-cand", attribute (Html.Attributes.attribute "data-yours" "true") ] |> Query.has [ attribute (Html.Attributes.attribute "data-rank" "2"), text "you" ]
                        , hasNot [ id "bg-action-play" ]
                        , hasNot [ id "bg-action-undo" ]
                        , has [ id "pz-share" ]
                        , hasNot [ id "pz-level" ]
                        ]
        , test "a pass and a miss wear their colours" <|
            \_ ->
                Expect.all
                    [ \_ -> rendered (after "move_pass") |> Query.find [ id "pz-verdict" ] |> Query.has [ class "is-pass", text "RIGHT" ]
                    , \_ -> rendered (after "move_fail") |> Query.find [ id "pz-verdict" ] |> Query.has [ class "is-fail", text "NOT THIS TIME" ]
                    ]
                    ()
        , test "unknown: the engine did not rank this one, the best move is named, nothing is marked yours" <|
            \_ ->
                rendered (after "move_unknown")
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-verdict" ] |> Query.has [ attribute (Html.Attributes.attribute "data-verdict" "unknown"), text "The engine did not rank this one." ]
                        , \q -> q |> Query.find [ id "pz-reveal" ] |> Query.has [ text "The best move here is play 1." ]
                        , hasNot [ class "rp-cand", attribute (Html.Attributes.attribute "data-yours" "true") ]
                        ]
        , test "a candidate goes on the board, and the move played comes back" <|
            \_ ->
                let
                    model =
                        after "move_hold"

                    showing =
                        step (Show (Just 1)) model
                in
                Expect.all
                    [ \_ -> rendered showing |> Query.find [ id "pz-board" ] |> Query.has [ class "is-proposed" ]
                    , \_ -> rendered showing |> Query.find [ class "rp-cand", attribute (Html.Attributes.attribute "data-rank" "1") ] |> Query.has [ class "is-on" ]
                    , \_ -> rendered (step (Show Nothing) showing) |> Query.find [ id "pz-board" ] |> Query.hasNot [ class "is-proposed" ]
                    ]
                    ()
        , test "the board no longer answers once the answer is in" <|
            \_ ->
                let
                    model =
                        after "move_hold"
                in
                (step (BoardOut Puzzle.Undo) model).path |> Expect.equal model.path
        ]



-- THE CUBE


cube : Test
cube =
    describe "a cube question"
        [ test "the five answers, worst for the cube first, in the side's words" <|
            \_ ->
                Expect.all
                    [ \_ ->
                        rendered (page { hasNext = False } "double")
                            |> Query.find [ id "pz-bands" ]
                            |> Query.findAll [ tag "button" ]
                            |> Query.count (Expect.equal 5)
                    , \_ ->
                        rendered (page { hasNext = False } "double")
                            |> Query.find [ id "pz-band-minus2" ]
                            |> Query.has [ text "Big no double" ]
                    , \_ ->
                        rendered (page { hasNext = False } "take")
                            |> Query.find [ id "pz-band-2" ]
                            |> Query.has [ text "Big take" ]
                    , \_ -> rendered (page { hasNext = False } "double") |> hasNot [ id "bg-action-play" ]
                    ]
                    ()
        , test "picking a band posts it with the key" <|
            \_ ->
                let
                    picked =
                        step (PickedBand 2) (page { hasNext = False } "double")
                in
                Expect.all
                    [ \_ -> picked.attempt |> Expect.equal Sending
                    , \_ -> Page.attemptBody picked |> Maybe.map (E.encode 0) |> Expect.equal (Just "{\"band\":2,\"key\":\"key-0123\"}")
                    ]
                    ()
        , test "the reveal marks the engine's band on the scale over the three equities" <|
            \_ ->
                let
                    model =
                        page { hasNext = False } "double" |> step (PickedBand 1) |> revealed (reveal "double_fail")
                in
                rendered model
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-verdict" ] |> Query.has [ attribute (Html.Attributes.attribute "data-verdict" "fail") ]
                        , hasNot [ id "pz-bands", tag "button" ]
                        , \q -> q |> Query.find [ id "pz-scale" ] |> Query.findAll [ attribute (Html.Attributes.attribute "data-engine" "true") ] |> Query.count (Expect.equal 1)
                        , \q -> q |> Query.find [ id "pz-scale" ] |> Query.find [ attribute (Html.Attributes.attribute "data-engine" "true") ] |> Query.has [ attribute (Html.Attributes.attribute "data-band" "2"), text "Big double" ]
                        , \q -> q |> Query.find [ id "pz-scale" ] |> Query.find [ attribute (Html.Attributes.attribute "data-band" "1") ] |> Query.has [ class "is-on" ]
                        , \q -> q |> Query.find [ class "rp-cube-eq", class "is-pick" ] |> Query.has [ text "Double, pass" ]
                        , \q -> q |> Query.find [ id "pz-reveal" ] |> Query.has [ text "White is winning here by enough that Black should pass." ]
                        ]
        , test "a take is answered from the taker's side" <|
            \_ ->
                rendered (page { hasNext = False } "take" |> step (PickedBand -2) |> revealed (reveal "take_pass"))
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-verdict" ] |> Query.has [ attribute (Html.Attributes.attribute "data-verdict" "pass") ]
                        , \q -> q |> Query.find [ id "pz-scale" ] |> Query.find [ attribute (Html.Attributes.attribute "data-engine" "true") ] |> Query.has [ text "Big pass" ]
                        , \q -> q |> Query.find [ id "pz-reveal" ] |> Query.has [ text "White is losing here by too much to take" ]
                        ]
        ]



-- THE LEVEL LINE


schedule : Test
schedule =
    let
        withSchedule name scheduleName =
            let
                model =
                    page { hasNext = False } "move"

                ( path, _ ) =
                    aTurn model
            in
            model
                |> step (BoardOut (Puzzle.Stepped path))
                |> revealed (revealWith name scheduleName)
                |> (\m -> { m | now = 1800000000000 - 7 * 86400000 })
    in
    describe "the level line"
        [ test "amendable: the line, and the graded button preselected (GOT IT on a hold)" <|
            \_ ->
                rendered (withSchedule "move_hold" "schedule_amendable")
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-level-line" ] |> Query.has [ text "Level 2 → 3 · back in 7 days" ]
                        , \q -> q |> Query.findAll [ id "pz-outcomes" ] |> Query.count (Expect.equal 1)
                        , \q -> q |> Query.find [ id "pz-outcome-got-it" ] |> Query.has [ attribute (Html.Attributes.attribute "aria-pressed" "true") ]
                        , \q -> q |> Query.findAll [ class "pz-outcome", attribute (Html.Attributes.attribute "aria-pressed" "true") ] |> Query.count (Expect.equal 1)
                        ]
        , test "amendable after a miss: SOONER is the graded one" <|
            \_ ->
                rendered (withSchedule "move_fail" "schedule_amendable")
                    |> Query.find [ id "pz-outcome-sooner" ]
                    |> Query.has [ attribute (Html.Attributes.attribute "aria-pressed" "true") ]
        , test "self-grade: the buttons, nothing preselected" <|
            \_ ->
                rendered (withSchedule "move_unknown" "schedule_self_grade")
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-level-line" ] |> Query.has [ text "Level 3 · back in 7 days" ]
                        , \q -> q |> Query.findAll [ id "pz-outcomes" ] |> Query.count (Expect.equal 1)
                        , \q -> q |> Query.findAll [ class "pz-outcome", attribute (Html.Attributes.attribute "aria-pressed" "true") ] |> Query.count (Expect.equal 0)
                        ]
        , test "settled: the line alone" <|
            \_ ->
                rendered (withSchedule "move_pass" "schedule_settled")
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-level-line" ] |> Query.has [ text "Level 1 · back in 7 days" ]
                        , hasNot [ id "pz-outcomes" ]
                        ]
        , test "a guest: no level line at all" <|
            \_ ->
                rendered (withSchedule "move_pass" "schedule_settled" |> revealed (reveal "move_pass")) |> hasNot [ id "pz-level" ]
        , test "an outcome that went through moves the line and the button" <|
            \_ ->
                let
                    model =
                        withSchedule "move_hold" "schedule_amendable"

                    -- What the override answers: the review replaced, still
                    -- amendable (the server's `schedule_json(_, _, _, True, False)`).
                    after =
                        D.decodeString Puzzle.scheduleDecoder (reveal "schedule_amendable")
                            |> Result.map (\s -> { s | levelBefore = 2, levelAfter = 0, due = model.now + 86400000 })
                            |> Result.toMaybe

                    pressed =
                        model |> step (PressedOutcome "sooner") |> step (GotOutcome "sooner" (Ok after))
                in
                rendered pressed
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-level-line" ] |> Query.has [ text "Level 2 → 0 · back tomorrow" ]
                        , \q -> q |> Query.find [ id "pz-outcome-sooner" ] |> Query.has [ attribute (Html.Attributes.attribute "aria-pressed" "true") ]
                        ]
        , test "an override that is refused says why, and the line stands" <|
            \_ ->
                let
                    pressed =
                        withSchedule "move_hold" "schedule_amendable"
                            |> step (PressedOutcome "knew_it")
                            |> step (GotOutcome "knew_it" (Err (Api.ApiError { code = "nothing_to_amend", message = "There is nothing to change about that answer" })))
                in
                rendered pressed
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-outcome-error" ] |> Query.has [ text "There is nothing to change about that answer" ]
                        , \q -> q |> Query.find [ id "pz-level-line" ] |> Query.has [ text "Level 2 → 3 · back in 7 days" ]
                        , \q -> q |> Query.find [ id "pz-outcome-got-it" ] |> Query.has [ attribute (Html.Attributes.attribute "aria-pressed" "true") ]
                        ]
        , test "NEVER: out of the deck, and the buttons go" <|
            \_ ->
                let
                    pressed =
                        withSchedule "move_hold" "schedule_amendable" |> step (PressedOutcome "never") |> step (GotOutcome "never" (Ok Nothing))
                in
                rendered pressed
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-level-line" ] |> Query.has [ text "Out of your deck" ]
                        , hasNot [ id "pz-outcomes" ]
                        ]
        , test "when it comes back, in words" <|
            \_ ->
                let
                    day =
                        86400000
                in
                Expect.all
                    [ \_ -> Page.backIn 0 day |> Expect.equal "back tomorrow"
                    , \_ -> Page.backIn 5000 day |> Expect.equal "back tomorrow"
                    , \_ -> Page.backIn 0 (3 * day) |> Expect.equal "back in 3 days"
                    , \_ -> Page.backIn 0 (365 * day) |> Expect.equal "back in a year"
                    , \_ -> Page.backIn 0 0 |> Expect.equal "back tomorrow"
                    ]
                    ()
        ]



-- NEXT


next : Test
next =
    let
        after config =
            let
                model =
                    page config "move"

                ( path, _ ) =
                    aTurn model
            in
            model |> step (BoardOut (Puzzle.Stepped path)) |> revealed (reveal "move_pass")
    in
    describe "NEXT"
        [ test "is there when the shell has a next puzzle, and asks the shell for it" <|
            \_ ->
                let
                    model =
                        after { hasNext = True }
                in
                Expect.all
                    [ \_ -> rendered model |> has [ id "pz-next" ]
                    , \_ -> out Next model |> Expect.equal Page.WantsNext
                    ]
                    ()
        , test "is absent on a puzzle opened on its own" <|
            \_ -> rendered (after { hasNext = False }) |> hasNot [ id "pz-next" ]
        , test "and never before the reveal" <|
            \_ -> rendered (page { hasNext = True } "move") |> hasNot [ id "pz-next" ]
        , test "but a puzzle of a run that did not load still offers it, so the run is not stranded" <|
            \_ ->
                let
                    missing config =
                        Page.init Session.empty { id = "gone", hasNext = config.hasNext, origin = "http://oskol.test", share = Nothing }
                            |> Tuple.first
                            |> step (GotPuzzle (Err (Api.ApiError { code = "not_found", message = "no" })))
                in
                Expect.all
                    [ \_ -> rendered (missing { hasNext = True }) |> has [ id "pz-missing", id "pz-next" ]
                    , \_ -> out Next (missing { hasNext = True }) |> Expect.equal Page.WantsNext
                    , \_ -> rendered (missing { hasNext = False }) |> hasNot [ id "pz-next" ]
                    ]
                    ()
        ]



-- THE END OF A RUN


practiceJson : String -> String
practiceJson counts =
    """{"ok":true,"puzzles":[],"cursor":null,"counts":""" ++ counts ++ ""","mistakes":null,"game":null}"""


moreJson : String
moreJson =
    """{"ok":true,"puzzles":[{"id":"aaaaaaaa","kind":"move","prompt":"White to play 6-4. What's your play?","due":true},{"id":"bbbbbbbb","kind":"move","prompt":"White to play 3-1. What's your play?","due":true}],"cursor":null,"counts":{"due":2,"new_today":0,"new_tomorrow":0,"deck":12},"mistakes":null,"game":null}"""


practice : String -> Result Api.Error Practice.Practice
practice =
    Api.parseBody Practice.practiceDecoder


account : Session.Session
account =
    Session.withUser (Just { email = "arie@example.com", name = Just "arie" }) Session.empty


{-| A page at the run's last puzzle, answered, with the shell's score
handed over.
-}
ended : Session.Session -> Page.Model
ended session =
    let
        ( model, _ ) =
            Page.init session { id = "fix", hasNext = True, origin = "http://oskol.test", share = Nothing }

        loaded =
            case D.decodeString Puzzle.decoder (question "move") of
                Ok p ->
                    GotPuzzle (Ok p)

                Err e ->
                    GotPuzzle (Err (Api.DecodeError (D.errorToString e)))

        answered =
            model |> step loaded |> step (GotKey "key-0123")

        ( path, _ ) =
            aTurn answered
    in
    answered
        |> step (BoardOut (Puzzle.Stepped path))
        |> revealed (reveal "move_pass")
        |> Page.endRun { right = 7, close = 2, total = 10 }
        |> Tuple.first


runEnd : Test
runEnd =
    describe "the end of a run"
        [ test "every verdict is reported to the shell, which keeps the score" <|
            \_ ->
                let
                    model =
                        page { hasNext = True } "move"

                    ( path, _ ) =
                        aTurn model

                    staged =
                        model |> step (BoardOut (Puzzle.Stepped path))
                in
                case decodeReveal (reveal "move_hold") of
                    Ok r ->
                        out (GotReveal (Ok r)) staged |> Expect.equal (Page.Answered Hold)

                    Err e ->
                        Expect.fail e
        , test "the score takes the board's place: right, and close" <|
            \_ ->
                rendered (ended Session.empty)
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-score" ] |> Query.has [ text "7 of 10 right" ]
                        , \q -> q |> Query.find [ id "pz-close" ] |> Query.has [ text "2 close" ]
                        , hasNot [ id "pz-board" ]
                        , hasNot [ id "pz-next" ]
                        ]
        , test "the words" <|
            \_ -> Page.runScore { right = 0, close = 0, total = 3 } |> Expect.equal "0 of 3 right"
        , test "a guest is asked to sign in, in the one component, going on to the practice home" <|
            \_ ->
                let
                    model =
                        ended Session.empty
                in
                Expect.all
                    [ \_ -> rendered model |> has [ id "pz-signin-ask" ]
                    , \_ -> rendered model |> has [ id "signin", id "signin-email" ]
                    , \_ -> rendered model |> hasNot [ id "pz-keep-going" ]
                    , \_ ->
                        case model.ended of
                            Just { after } ->
                                case after of
                                    Page.AskSignIn signIn ->
                                        Expect.equal "/puzzles" signIn.next

                                    _ ->
                                        Expect.fail "a guest's end is the sign-in"

                            Nothing ->
                                Expect.fail "the run has not ended"
                    ]
                    ()
        , test "a sign-in that went through is the shell's to note, and CONTINUE goes to the home" <|
            \_ ->
                let
                    won =
                        { saved = 1, next = "/puzzles", user = Just { email = "arie@example.com", name = Just "arie" }, new = False }
                in
                Expect.all
                    [ \_ -> out (EndSignInMsg (SignIn.GotCode (Ok won))) (ended Session.empty) |> Expect.equal (Page.SignedIn won.user)
                    , \_ ->
                        ended Session.empty
                            |> step (EndSignInMsg (SignIn.GotCode (Ok won)))
                            |> out (EndSignInMsg SignIn.PressedContinue)
                            |> Expect.equal (Page.Go "/puzzles")
                    ]
                    ()
        , test "an account asks its deck what is left; nothing is done for today, with KEEP GOING" <|
            \_ ->
                let
                    model =
                        ended account
                in
                Expect.all
                    [ \_ -> rendered model |> hasNot [ id "signin" ]
                    , \_ -> rendered model |> has [ text "ASKING YOUR DECK…" ]
                    , \_ ->
                        model
                            |> step (GotLeft (practice (practiceJson """{"due":0,"new_today":0,"new_tomorrow":4,"deck":231}""")))
                            |> rendered
                            |> Expect.all
                                [ \q -> q |> Query.find [ id "pz-done" ] |> Query.has [ text "Done for today. 4 new tomorrow." ]
                                , has [ id "pz-keep-going" ]
                                , hasNot [ id "pz-nothing-more" ]
                                ]
                    ]
                    ()
        , test "KEEP GOING starts what it brought, and CONTINUE what was already left" <|
            \_ ->
                let
                    done =
                        ended account |> step (GotLeft (practice (practiceJson """{"due":0,"new_today":0,"new_tomorrow":4,"deck":231}""")))
                in
                Expect.all
                    [ \_ -> done |> step PressedKeepGoing |> out (GotMore (practice moreJson)) |> Expect.equal (Page.StartRun [ "aaaaaaaa", "bbbbbbbb" ])
                    , \_ -> done |> step PressedKeepGoing |> rendered |> Query.find [ id "pz-keep-going" ] |> Query.has [ attribute (Html.Attributes.disabled True) ]
                    , \_ ->
                        let
                            left =
                                ended account |> step (GotLeft (practice moreJson))
                        in
                        Expect.all
                            [ \_ -> rendered left |> Query.find [ id "pz-more-due" ] |> Query.has [ text "2 more to go." ]
                            , \_ -> out PressedContinueRun left |> Expect.equal (Page.StartRun [ "aaaaaaaa", "bbbbbbbb" ])
                            ]
                            ()
                    ]
                    ()
        , test "a deck with nothing more to start says so, once KEEP GOING has asked" <|
            \_ ->
                let
                    nothingNew =
                        ended account
                            |> step (GotLeft (practice (practiceJson """{"due":0,"new_today":0,"new_tomorrow":0,"deck":12}""")))
                in
                Expect.all
                    [ \_ ->
                        rendered nothingNew
                            |> Expect.all
                                [ \q -> q |> Query.find [ id "pz-done" ] |> Query.has [ text "Done for today." ]
                                , \q -> q |> Query.find [ id "pz-done" ] |> Query.hasNot [ text "tomorrow" ]
                                , has [ id "pz-keep-going" ]
                                , hasNot [ id "pz-nothing-more" ]
                                ]
                    , \_ ->
                        nothingNew
                            |> step PressedKeepGoing
                            |> step (GotMore (practice (practiceJson """{"due":0,"new_today":0,"new_tomorrow":0,"deck":12}""")))
                            |> rendered
                            |> Expect.all
                                [ has [ id "pz-nothing-more" ]
                                , hasNot [ id "pz-keep-going" ]
                                ]
                    ]
                    ()
        ]



-- THE MEMORY LINE


memoryJson : String
memoryJson =
    """{"ok":true,"who":"you","opponent":"Charlie","played":"24/23 13/11","equity_lost":0.11,"grade":"bad","date":"2026-09-12","result":{"won":false,"points":2},"replay":"/backgammon/000011/replay?game=2&step=6"}"""


memory : Test
memory =
    let
        after =
            let
                model =
                    page { hasNext = False } "move"

                ( path, _ ) =
                    aTurn model
            in
            model |> step (BoardOut (Puzzle.Stepped path)) |> revealed (reveal "move_fail")

        got body =
            case Api.parseBody Puzzle.memoryDecoder body of
                Ok m ->
                    GotMemory (Ok m)

                Err e ->
                    GotMemory (Err e)
    in
    describe "the memory line"
        [ test "on a 200: the sentence and the link to the moment in the replay" <|
            \_ ->
                rendered (step (got memoryJson) after)
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-memory" ] |> Query.has [ text "From your game vs Charlie, 12 Sep. You played 24/23 13/11 (a bad move) and lost 2 points." ]
                        , \q -> q |> Query.find [ id "pz-memory-link" ] |> Query.has [ attribute (Html.Attributes.href "/backgammon/000011/replay?game=2&step=6") ]
                        ]
        , test "the opponent's mistake, by name, and a win" <|
            \_ ->
                Page.memoryLine
                    { who = "Charlie", opponent = "Charlie", played = "8/2 6/2", equityLost = 0.05, grade = "doubtful", date = "2026-01-03", result = Just { won = True, points = 1 }, replay = "/x" }
                    |> Expect.equal "From your game vs Charlie, 3 Jan. Charlie played 8/2 6/2 (a dubious move) and you won 1 point."
        , test "a memory line without an opponent to name, or a result, still reads" <|
            \_ ->
                Page.memoryLine
                    { who = "you", opponent = "", played = "8/2 6/2", equityLost = 0.11, grade = "bad", date = "2026-01-03", result = Nothing, replay = "/x" }
                    |> Expect.equal "From your game, 3 Jan. You played 8/2 6/2 (a bad move)."
        , test "a memory line missing the opponent fails to decode rather than naming nobody" <|
            \_ ->
                Api.parseBody Puzzle.memoryDecoder (String.replace "\"opponent\":\"Charlie\"," "" memoryJson)
                    |> Result.toMaybe
                    |> Expect.equal Nothing
        , test "on a 404: nothing, silently" <|
            \_ ->
                rendered (step (got """{"ok":false,"error":{"code":"not_found","message":"You were not in the game that puzzle came from"}}""") after)
                    |> hasNot [ id "pz-memory" ]
        , test "and never before the attempt" <|
            \_ -> rendered (page { hasNext = False } "move") |> hasNot [ id "pz-memory" ]
        ]



-- SHARING


{-| The memory line as the opponent reads it: the mistake was Charlie's.
-}
theirMemoryJson : String
theirMemoryJson =
    String.replace "\"who\":\"you\"" "\"who\":\"Charlie\"" memoryJson


sharing : Test
sharing =
    let
        revealedPage =
            let
                model =
                    page { hasNext = False } "move"

                ( path, _ ) =
                    aTurn model
            in
            model |> step (BoardOut (Puzzle.Stepped path)) |> revealed (reveal "move_fail")

        got body =
            case Api.parseBody Puzzle.memoryDecoder body of
                Ok m ->
                    GotMemory (Ok m)

                Err e ->
                    GotMemory (Err e)
    in
    describe "Share with my mistake"
        [ test "is offered to the player whose own mistake it was" <|
            \_ ->
                rendered (step (got memoryJson) revealedPage)
                    |> Expect.all
                        [ has [ id "pz-share" ]
                        , \q -> q |> Query.find [ id "pz-share-story" ] |> Query.has [ text "SHARE WITH MY MISTAKE" ]
                        ]
        , test "and not to the opponent, who has a memory line of their own" <|
            \_ -> rendered (step (got theirMemoryJson) revealedPage) |> hasNot [ id "pz-share-story" ]
        , test "nor to a stranger, who has none" <|
            \_ ->
                rendered (step (got """{"ok":false,"error":{"code":"not_found","message":"no"}}""") revealedPage)
                    |> Expect.all [ has [ id "pz-share" ], hasNot [ id "pz-share-story" ] ]
        , test "and never before the reveal" <|
            \_ -> rendered (page { hasNext = False } "move") |> hasNot [ id "pz-share-story" ]
        , test "the button says what the share sheet answered, and SHARE's label is left alone" <|
            \_ ->
                rendered (revealedPage |> step (got memoryJson) |> step ShareStory |> step (GotShare (Ok "/puzzles/fix?s=TOKEN0000001")) |> step (ShareReported "copied"))
                    |> Expect.all
                        [ \q -> q |> Query.find [ id "pz-share-story" ] |> Query.has [ text "Copied" ]
                        , \q -> q |> Query.find [ id "pz-share" ] |> Query.has [ text "SHARE" ]
                        ]
        , test "a refusal says so" <|
            \_ ->
                rendered (revealedPage |> step (got memoryJson) |> step ShareStory |> step (GotShare (Err (Api.ApiError { code = "forbidden", message = "Only the player who made this mistake can share it" }))))
                    |> Query.find [ id "pz-share-story" ]
                    |> Query.has [ text "Copy failed" ]
        ]



-- THE STORY


storyJson : String
storyJson =
    """{"name":"Arie","kind":"move","played":"24/23 13/11","grade":"bad","equity_lost":0.11,"date":"2026-09-12","result":{"won":false,"points":2},"headline":"Arie got this wrong. What's your play?","line":"Arie played 24/23 13/11 (a bad move) and lost 2 points."}"""


{-| The reveal a page opened with `?s=` gets: the same answer, with the
story where the plain page's `null` was.
-}
revealWithStory : String -> String
revealWithStory name =
    String.replace "\"story\":null" ("\"story\":" ++ storyJson) (reveal name)


story : Test
story =
    let
        opened share =
            let
                ( model, _ ) =
                    Page.init Session.empty { id = "fix", hasNext = False, origin = "http://oskol.test", share = share }

                loaded =
                    case D.decodeString Puzzle.decoder (question "move") of
                        Ok p ->
                            GotPuzzle (Ok p)

                        Err e ->
                            GotPuzzle (Err (Api.DecodeError (D.errorToString e)))

                withKey =
                    model |> step loaded |> step (GotKey "key-0123")

                ( path, _ ) =
                    aTurn withKey
            in
            withKey |> step (BoardOut (Puzzle.Stepped path))
    in
    describe "the story a share link tells"
        [ test "the token the page was opened with rides on the attempt" <|
            \_ ->
                Page.attemptBody (opened (Just "TOKEN0000001"))
                    |> Maybe.map (E.encode 0)
                    |> Maybe.map (String.contains "\"s\":\"TOKEN0000001\"")
                    |> Expect.equal (Just True)
        , test "and a plain page sends none" <|
            \_ ->
                Page.attemptBody (opened Nothing)
                    |> Maybe.map (E.encode 0)
                    |> Maybe.map (String.contains "\"s\":")
                    |> Expect.equal (Just False)
        , test "the reveal shows the story in the server's words, under the reveal" <|
            \_ ->
                rendered (opened (Just "TOKEN0000001") |> revealed (revealWithStory "move_fail"))
                    |> Query.find [ id "pz-story" ]
                    |> Query.has [ text "Arie played 24/23 13/11 (a bad move) and lost 2 points." ]
        , test "and nothing where the answer carries none" <|
            \_ -> rendered (opened Nothing |> revealed (reveal "move_fail")) |> hasNot [ id "pz-story" ]
        , test "a story missing its line fails the reveal rather than showing nothing" <|
            \_ ->
                decodeReveal (String.replace ",\"line\":\"Arie played 24/23 13/11 (a bad move) and lost 2 points.\"" "" (revealWithStory "move_fail"))
                    |> Result.toMaybe
                    |> Expect.equal Nothing
        , test "every fixture reveal decodes with the story slot present and empty" <|
            \_ ->
                [ "move_pass", "move_fail", "double_fail", "take_pass" ]
                    |> List.map (\n -> decodeReveal (reveal n) |> Result.map .story)
                    |> Expect.equal (List.repeat 4 (Ok Nothing))
        ]
