module PuzzleApiTest exposing (suite)

{-| The server's own answers, decoded by the page's own decoder.

`BackgammonPuzzleTest` drives the board from a hand-written tree, which
says what the client does with a payload but nothing about whether the
server sends that shape. This does the other half: `PuzzleApiFixtures` is
generated by `mix oskol.fixtures` straight out of
`oskol/handlers/puzzles`, so if either side of the frozen wire contract
moves, this fails.

Every fact asserted here is one the contract states. Nothing here knows a
rule of backgammon -- that the tree is *right* is the server's suite's
business; that it is well formed and decodable is this one's.

-}

import Dict
import Expect
import Games.Backgammon.Puzzle as Puzzle
import Json.Decode as D
import PuzzleApiFixtures
import Set
import Test exposing (Test, describe, test)


suite : Test
suite =
    describe "GET /papi/puzzles/:id, as the server sends it"
        [ describe "every fixture decodes" (List.map decodes PuzzleApiFixtures.all)
        , describe "every tree is walkable" (List.map walkable PuzzleApiFixtures.all)
        , describe "the answer is never in it" (List.map silent PuzzleApiFixtures.all)
        , kinds
        ]


puzzle : String -> Result String Puzzle.Puzzle
puzzle body =
    D.decodeString Puzzle.decoder body |> Result.mapError D.errorToString


decodes : ( String, String ) -> Test
decodes ( name, body ) =
    test name <|
        \_ ->
            case puzzle body of
                Err message ->
                    Expect.fail message

                Ok p ->
                    Expect.all
                        [ \_ -> p.id |> Expect.notEqual ""
                        , \_ -> p.prompt |> Expect.notEqual ""
                        , \_ -> List.length p.question.board.white.points |> Expect.equal 24
                        , \_ -> List.length p.question.board.black.points |> Expect.equal 24

                        -- Fifteen checkers a side, always.
                        , \_ -> checkers p.question.board.white |> Expect.equal 15
                        , \_ -> checkers p.question.board.black |> Expect.equal 15
                        ]
                        ()


checkers : Puzzle.Side -> Int
checkers side =
    List.sum side.points + side.bar + side.off


{-| The page walks the tree by node id, so every child has to name a node
the tree holds, the root has to be one of them, and `terminal` has to mean
"no children" -- which is where PLAY is offered.
-}
walkable : ( String, String ) -> Test
walkable ( name, body ) =
    test name <|
        \_ ->
            case Result.map .tree (puzzle body) of
                Err message ->
                    Expect.fail message

                Ok Nothing ->
                    -- A cube question has no moves to make.
                    Expect.pass

                Ok (Just tree) ->
                    let
                        nodes =
                            Dict.toList tree.nodes

                        missing =
                            nodes
                                |> List.concatMap (Tuple.second >> .children)
                                |> List.filter (\c -> not (Dict.member c.node tree.nodes))
                    in
                    Expect.all
                        [ \_ -> Dict.member tree.root tree.nodes |> Expect.equal True
                        , \_ -> List.map .node missing |> Expect.equal []
                        , \_ -> tree.lazy |> Expect.equal False

                        -- terminal is exactly "nothing more can be played".
                        , \_ ->
                            nodes
                                |> List.filter (\( _, n ) -> n.terminal /= (n.children == []))
                                |> List.map Tuple.first
                                |> Expect.equal []

                        -- The root is the question itself: nothing has moved.
                        , \_ ->
                            Dict.get tree.root tree.nodes
                                |> Maybe.andThen .moved
                                |> Expect.equal Nothing

                        -- Every other node was reached by a step.
                        , \_ ->
                            nodes
                                |> List.filter (\( id, n ) -> id /= tree.root && n.moved == Nothing)
                                |> List.map Tuple.first
                                |> Expect.equal []

                        -- A child's die is one the node still had to play.
                        , \_ ->
                            nodes
                                |> List.filter
                                    (\( _, n ) ->
                                        List.any (\c -> not (List.member c.die n.diceLeft)) n.children
                                    )
                                |> List.map Tuple.first
                                |> Expect.equal []

                        -- Fifteen a side in every node too: a tree that
                        -- loses a checker has applied a move wrongly.
                        , \_ ->
                            nodes
                                |> List.filter
                                    (\( _, n ) ->
                                        checkers n.board.white /= 15 || checkers n.board.black /= 15
                                    )
                                |> List.map Tuple.first
                                |> Expect.equal []
                        ]
                        ()


{-| A puzzle page shows nobody the answer, and marks no move as the one
that was played: the payload has to carry neither.
-}
silent : ( String, String ) -> Test
silent ( name, body ) =
    test name <|
        \_ ->
            let
                says word =
                    String.contains word body
            in
            [ "equity", "candidates", "outcomes", "played", "notation", "probs" ]
                |> List.filter says
                |> Expect.equal []


kinds : Test
kinds =
    describe "the question each kind asks"
        [ test "a checker play names its roll" <|
            \_ ->
                on "move"
                    (\p ->
                        Expect.all
                            [ \_ -> p.kind |> Expect.equal "move"
                            , \_ -> p.prompt |> Expect.equal "White to play 6-4. What's your play?"
                            , \_ -> p.question.dice |> Expect.equal [ 6, 4 ]
                            , \_ -> p.tree |> Expect.notEqual Nothing
                            ]
                            ()
                    )
        , test "a doubles roll is four dice to play" <|
            \_ ->
                on "doubles"
                    (\p ->
                        Expect.all
                            [ \_ -> p.prompt |> Expect.equal "White to play 3-3. What's your play?"
                            , \_ -> p.question.dice |> Expect.equal [ 3, 3 ]
                            , \_ ->
                                p.tree
                                    |> Maybe.andThen (\t -> Dict.get t.root t.nodes)
                                    |> Maybe.map .diceLeft
                                    |> Expect.equal (Just [ 3, 3, 3, 3 ])
                            ]
                            ()
                    )
        , test "every order of the same checkers is one node" <|
            \_ ->
                on "doubles"
                    (\p ->
                        case p.tree of
                            Nothing ->
                                Expect.fail "no tree"

                            Just tree ->
                                -- More edges than nodes is the merge: the
                                -- orders meet again rather than branching
                                -- for ever.
                                Dict.toList tree.nodes
                                    |> List.concatMap (Tuple.second >> .children)
                                    |> List.map .node
                                    |> Set.fromList
                                    |> Set.size
                                    |> Expect.lessThan
                                        (Dict.toList tree.nodes
                                            |> List.concatMap (Tuple.second >> .children)
                                            |> List.length
                                        )
                    )
        , test "a cube question has no dice and no tree" <|
            \_ ->
                on "double"
                    (\p ->
                        Expect.all
                            [ \_ -> p.kind |> Expect.equal "double"
                            , \_ -> p.prompt |> Expect.equal "Double?"
                            , \_ -> p.question.dice |> Expect.equal []
                            , \_ -> p.tree |> Expect.equal Nothing
                            ]
                            ()
                    )
        , test "a take is asked of the responder, so the cube is the opponent's" <|
            \_ ->
                on "take"
                    (\p ->
                        Expect.all
                            [ \_ -> p.kind |> Expect.equal "take"
                            , \_ -> p.prompt |> Expect.equal "Take?"

                            -- Stored from the doubler's side, shown from
                            -- the responder's: the cube changes hands and
                            -- the away scores swap with it.
                            , \_ -> p.question.cube |> Expect.equal { value = 2, owner = "opponent" }
                            , \_ ->
                                p.question.score
                                    |> Expect.equal (Just { moverAway = 5, opponentAway = 3 })
                            ]
                            ()
                    )
        ]


on : String -> (Puzzle.Puzzle -> Expect.Expectation) -> Expect.Expectation
on name check =
    case PuzzleApiFixtures.all |> List.filter (\( n, _ ) -> n == name) |> List.head of
        Nothing ->
            Expect.fail ("no fixture named " ++ name)

        Just ( _, body ) ->
            case puzzle body of
                Err message ->
                    Expect.fail message

                Ok p ->
                    check p
