import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :oskol, OskolWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Set up sentry config
# - refer to: https://arie-milner.sentry.io/insights/projects/oskol/getting-started
config :sentry,
  dsn:
    "https://f8fa809a8c03794cd455b50a6021cb75@o4510418103894016.ingest.us.sentry.io/4510418104221696",
  environment_name: Mix.env(),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]
