module GameArt exposing
    ( Rect
    , accent
    , art
    , frameCount
    , framesFor
    , motif
    , rects
    )

{-| Per-game presentation for the library: a notebook-palette accent and a
small piece of pixel art drawn from a character grid. A direct port of
`OskolWeb.GameArt` (which the SPA replaced) — same grids, same palette, same
markup and class names.

A game's art is a list of frames. They are stacked into a reel and cycled by
one CSS `steps()` animation on a single transform: no JavaScript, nothing to
schedule on a phone. `prefers-reduced-motion` drops the animation, which
leaves the first frame showing.

The grid is decomposed into as few `<rect>`s as it can be: equal neighbours
merge along a row, then identical runs merge down the rows, so a solid
background costs one rect instead of a thousand. The Elixir version did this
at compile time; here it is `rects`, memoised per art node by `Html.Lazy`.

-}

import Html exposing (Html)
import Html.Attributes exposing (attribute, class)
import Html.Lazy
import Set exposing (Set)
import Svg
import Svg.Attributes as SvgAttr


{-| How long one frame of a game's art is held.
-}
frameMs : Int
frameMs =
    800


{-| A rectangle covering a run of equal cells.
-}
type alias Rect =
    { x : Int
    , y : Int
    , w : Int
    , h : Int
    , color : String
    }



-- PALETTE AND ACCENTS


{-| Notebook palette: pen blue, red pen, highlighter, pencil, marker colours.
-}
colorFor : Char -> String
colorFor char =
    case char of
        'W' ->
            "#ffffff"

        'K' ->
            "#23243a"

        'L' ->
            "#3d3f5c"

        'R' ->
            "#e3453b"

        'B' ->
            "#2f5fd0"

        'Y' ->
            "#ffd93d"

        'G' ->
            "#62c370"

        'P' ->
            "#f27ba1"

        'S' ->
            "#6ec1ff"

        'T' ->
            "#f1dcb3"

        'N' ->
            "#b97a4f"

        'E' ->
            "#43286e"

        'M' ->
            "#7d4fc9"

        'C' ->
            "#e8f1f7"

        'A' ->
            "#3fa7d6"

        'Z' ->
            "#1a5a7d"

        'D' ->
            "#8fcbe8"

        'X' ->
            "#7a4a28"

        _ ->
            "#000"


{-| Accent colour for a game slug.
-}
accent : String -> String
accent slug =
    case slug of
        "poker" ->
            "#7d4fc9"

        "backgammon" ->
            "#3fa7d6"

        "chess" ->
            "#3d3f5c"

        "go" ->
            "#b97a4f"

        _ ->
            "#6b6b78"



-- DECOMPOSITION


type alias Run =
    { x : Int
    , w : Int
    , color : String
    }


{-| Rectangles covering every non-`.` cell of a character grid.
-}
rects : List String -> List Rect
rects rows =
    rows
        |> List.indexedMap (\y row -> ( y, runs row ))
        |> List.foldl absorbRow ( [], [] )
        |> (\( closed, open ) -> closed ++ open)


{-| The runs of equal, non-blank cells in one row.
-}
runs : String -> List Run
runs row =
    let
        step char ( x, current, done ) =
            case current of
                Just r ->
                    if r.char == char then
                        ( x + 1, Just { r | w = r.w + 1 }, done )

                    else
                        ( x + 1, Just { char = char, x = x, w = 1 }, r :: done )

                Nothing ->
                    ( x + 1, Just { char = char, x = x, w = 1 }, done )

        ( _, last, acc ) =
            String.foldl step ( 0, Nothing, [] ) row
    in
    (case last of
        Just r ->
            r :: acc

        Nothing ->
            acc
    )
        |> List.reverse
        |> List.filter (\r -> r.char /= '.')
        |> List.map (\r -> { x = r.x, w = r.w, color = colorFor r.char })


{-| A run directly under an open rect of the same span and colour extends it;
anything else opens a rect, and any open rect it did not extend is done.
-}
absorbRow : ( Int, List Run ) -> ( List Rect, List Rect ) -> ( List Rect, List Rect )
absorbRow ( y, rowRuns ) ( closed, open ) =
    let
        spans : Set ( Int, Int, String )
        spans =
            Set.fromList (List.map runSpan rowRuns)

        ( extending, finished ) =
            List.partition (\r -> Set.member (rectSpan r) spans) open

        extended =
            List.map (\r -> { r | h = r.h + 1 }) extending

        kept : Set ( Int, Int, String )
        kept =
            Set.fromList (List.map rectSpan extended)

        fresh =
            rowRuns
                |> List.filter (\r -> not (Set.member (runSpan r) kept))
                |> List.map (\r -> { x = r.x, y = y, w = r.w, h = 1, color = r.color })
    in
    ( finished ++ closed, extended ++ fresh )


runSpan : Run -> ( Int, Int, String )
runSpan r =
    ( r.x, r.w, r.color )


rectSpan : Rect -> ( Int, Int, String )
rectSpan r =
    ( r.x, r.w, r.color )



-- ART


{-| Number of frames in a game's art. For tests.
-}
frameCount : String -> Int
frameCount slug =
    List.length (framesFor slug)


{-| Pixel art for the game as crisp SVG rectangles. With `animate` the frames
are stacked into a reel that a single keyframe animation steps through;
without it only the first frame is rendered.
-}
art : { slug : String, class : String, animate : Bool } -> Html msg
art config =
    Html.Lazy.lazy3 artNode config.slug config.class config.animate


artNode : String -> String -> Bool -> Html msg
artNode slug extraClass animate =
    let
        allFrames =
            framesFor slug

        first =
            List.head allFrames |> Maybe.withDefault []

        shown =
            if animate then
                allFrames

            else
                List.take 1 allFrames

        count =
            List.length shown

        width =
            first |> List.head |> Maybe.map String.length |> Maybe.withDefault 1

        height =
            List.length first

        viewBox =
            "0 0 " ++ String.fromInt width ++ " " ++ String.fromInt height
    in
    Html.div
        [ class
            (String.join " "
                (List.filter (not << String.isEmpty)
                    [ "game-art"
                    , if count > 1 then
                        "game-art-anim"

                      else
                        ""
                    , extraClass
                    ]
                )
            )
        , attribute "style"
            ("aspect-ratio: "
                ++ String.fromInt width
                ++ " / "
                ++ String.fromInt height
                ++ "; --art-frames: "
                ++ String.fromInt count
                ++ "; --art-duration: "
                ++ String.fromInt (count * frameMs)
                ++ "ms"
            )
        , attribute "aria-hidden" "true"
        ]
        [ Html.div [ class "game-art-reel" ]
            (List.map (frameSvg viewBox) shown)
        ]


frameSvg : String -> List String -> Html msg
frameSvg viewBox rows =
    Svg.svg
        [ SvgAttr.viewBox viewBox, SvgAttr.shapeRendering "crispEdges" ]
        (List.map rectSvg (rects rows))


rectSvg : Rect -> Html msg
rectSvg r =
    Svg.rect
        [ SvgAttr.x (String.fromInt r.x)
        , SvgAttr.y (String.fromInt r.y)
        , SvgAttr.width (String.fromInt r.w)
        , SvgAttr.height (String.fromInt r.h)
        , SvgAttr.fill r.color
        ]
        []



-- MOTIF


{-| The phone-sized motif: one game drawn as a few lines. The library's pixel
art is a reel of frames per game, which is the point of it on a desktop
screen and far too much on a phone, so the small grid uses these instead: no
animation, no sprite decomposition, a handful of nodes. Strokes are the
notebook ink and the game's own accent (`--accent`, set by the tile), so
nothing here introduces a colour.
-}
motif : String -> String -> Html msg
motif slug extraClass =
    Svg.svg
        [ SvgAttr.class (String.join " " (List.filter (not << String.isEmpty) [ "game-motif", extraClass ]))
        , SvgAttr.viewBox "0 0 64 64"
        , SvgAttr.fill "none"
        , SvgAttr.stroke "var(--ink)"
        , SvgAttr.strokeWidth "2"
        , SvgAttr.strokeLinecap "round"
        , SvgAttr.strokeLinejoin "round"
        , attribute "aria-hidden" "true"
        ]
        (motifShapes slug)


motifShapes : String -> List (Html msg)
motifShapes slug =
    case slug of
        -- Five cards fanned from one corner, the front one showing a pip.
        "poker" ->
            [ Svg.g [ SvgAttr.transform "translate(32 50)" ]
                (List.map
                    (\angle ->
                        Svg.rect
                            [ SvgAttr.x "-8"
                            , SvgAttr.y "-26"
                            , SvgAttr.width "16"
                            , SvgAttr.height "24"
                            , SvgAttr.rx "2.5"
                            , SvgAttr.fill "#fff"
                            , SvgAttr.transform ("rotate(" ++ String.fromInt angle ++ ")")
                            ]
                            []
                    )
                    [ -36, -18, 0, 18, 36 ]
                    ++ [ Svg.path [ SvgAttr.d "M0 -18 5 -12 0 -6 -5 -12Z", SvgAttr.stroke "var(--accent)" ] [] ]
                )
            ]

        -- Three points and two checkers: a board reduced to its silhouette.
        "backgammon" ->
            [ Svg.path
                [ SvgAttr.d "M12 14 26 14 19 40Z"
                , SvgAttr.fill "var(--accent)"
                , SvgAttr.fillOpacity "0.3"
                , SvgAttr.stroke "var(--accent)"
                ]
                []
            , Svg.path [ SvgAttr.d "M26 14 40 14 33 40Z", SvgAttr.fill "#fff" ] []
            , Svg.path
                [ SvgAttr.d "M40 14 54 14 47 40Z"
                , SvgAttr.fill "var(--accent)"
                , SvgAttr.fillOpacity "0.3"
                , SvgAttr.stroke "var(--accent)"
                ]
                []
            , Svg.path [ SvgAttr.d "M11 46 53 46" ] []
            , Svg.circle [ SvgAttr.cx "25", SvgAttr.cy "54", SvgAttr.r "6", SvgAttr.fill "#fff" ] []
            , Svg.circle [ SvgAttr.cx "41", SvgAttr.cy "54", SvgAttr.r "6", SvgAttr.fill "var(--ink)" ] []
            ]

        -- The knight, outlined: muzzle, ear, mane, plinth.
        "chess" ->
            [ Svg.path [ SvgAttr.d "M22 50h20l2 6H20Z" ] []
            , Svg.path [ SvgAttr.d "M40 50c1-8 1-14-1-19s-5-10-8-14l-1-5-4 5c-4 1-7 3-10 7l-3 5c0 2 1 3 3 3l4-1 2 3-2 4c-1 4-2 8-2 12" ] []
            , Svg.path [ SvgAttr.d "M31 20c-3 4-5 8-6 12", SvgAttr.stroke "var(--accent)" ] []
            , Svg.circle
                [ SvgAttr.cx "26", SvgAttr.cy "26", SvgAttr.r "1.2", SvgAttr.fill "var(--ink)", SvgAttr.stroke "none" ]
                []
            ]

        -- Stones on the lines: the board in accent, the play in ink and white.
        "go" ->
            [ Svg.g [ SvgAttr.stroke "var(--accent)", SvgAttr.strokeWidth "1.5" ]
                (List.map (\n -> Svg.path [ SvgAttr.d ("M" ++ String.fromInt n ++ " 14V50") ] []) [ 14, 26, 38, 50 ]
                    ++ List.map (\n -> Svg.path [ SvgAttr.d ("M14 " ++ String.fromInt n ++ "H50") ] []) [ 14, 26, 38, 50 ]
                )
            , Svg.circle [ SvgAttr.cx "26", SvgAttr.cy "26", SvgAttr.r "6", SvgAttr.fill "var(--ink)" ] []
            , Svg.circle [ SvgAttr.cx "38", SvgAttr.cy "38", SvgAttr.r "6", SvgAttr.fill "#fff" ] []
            ]

        -- A game with no motif of its own: a piece on a square.
        _ ->
            [ Svg.rect [ SvgAttr.x "14", SvgAttr.y "14", SvgAttr.width "36", SvgAttr.height "36", SvgAttr.rx "3" ] []
            , Svg.circle [ SvgAttr.cx "32", SvgAttr.cy "32", SvgAttr.r "8", SvgAttr.stroke "var(--accent)" ] []
            ]



-- FRAMES
--
-- Each game is a storyboard: the frames loop, so the last frame reads as the
-- moment before the first.


{-| The frames of a game's art, or a generic sprite for a game with none.
-}
framesFor : String -> List (List String)
framesFor slug =
    case slug of
        "poker" ->
            pokerFrames

        "backgammon" ->
            backgammonFrames

        "chess" ->
            chessFrames

        "go" ->
            goFrames

        _ ->
            defaultFrames


pokerFrames : List (List String)
pokerFrames =
    [ [ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      ]
    , [ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEKKKKKEKKKKKEKKKKKEEEEEEEEEEEEEEM"
      , "MEKWWWKEKWWWKEKWWWKEEEEEEEEEEEEEEM"
      , "MEKWRWKEKWKWKEKWRWKEEEEEEEEEEEEEEM"
      , "MEKRRRKEKKKKKEKRRRKEEEEEEEEEEEEEEM"
      , "MEKWRWKEKWKWKEKWRWKEEEEEEEEEEEEEEM"
      , "MEKWWWKEKWWWKEKWWWKEEEEEEEEEEEEEEM"
      , "MEKKKKKEKKKKKEKKKKKEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKRRRKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      ]
    , [ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEKKKKKEKKKKKEKKKKKEKKKKKEEEEEEEEM"
      , "MEKWWWKEKWWWKEKWWWKEKWWWKEEEEEEEEM"
      , "MEKWRWKEKWKWKEKWRWKEKWKWKEEEEEEEEM"
      , "MEKRRRKEKKKKKEKRRRKEKKKKKEEEEEEEEM"
      , "MEKWRWKEKWKWKEKWRWKEKWKWKEEEEEEEEM"
      , "MEKWWWKEKWWWKEKWWWKEKWWWKEEEEEEEEM"
      , "MEKKKKKEKKKKKEKKKKKEKKKKKEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKRRRKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      ]
    , [ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKSBSKEKSBSKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKBSBKEKBSBKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM"
      , "MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM"
      , "MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM"
      , "MEKRRRKEKKKKKEKRRRKEKKKKKEKRRRKEEM"
      , "MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM"
      , "MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM"
      , "MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKRRRKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      ]
    , [ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWKWKEKWRWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKRRRKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWKWKEKWRWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEERRRRREEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM"
      , "MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM"
      , "MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM"
      , "MEKRRRKEKKKKKEKRRRKEKKKKKEKRRRKEEM"
      , "MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM"
      , "MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM"
      , "MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKRRRKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      ]
    , [ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWKWKEKWRWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKRRRKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWKWKEKWRWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM"
      , "MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM"
      , "MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM"
      , "MEKRRRKEKKKKKEKRRRKEKKKKKEKRRRKEEM"
      , "MEKWRWKEKWKWKEKWRWKEKWKWKEKWRWKEEM"
      , "MEKWWWKEKWWWKEKWWWKEKWWWKEKWWWKEEM"
      , "MEKKKKKEKKKKKEKKKKKEKKKKKEKKKKKEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKWRWKEKWKWKEEEEEEEEEEEM"
      , "MEEEEEEEEEEKRRRKEKKKKKEEEYYYYYEEEM"
      , "MEEEEEEEEEEKWRWKEKWKWKEEERRRRREEEM"
      , "MEEEEEEEEEEKWWWKEKWWWKEEEYYYYYEEEM"
      , "MEEEEEEEEEEKKKKKEKKKKKEEERRRRREEEM"
      , "MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEM"
      , "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      ]
    ]


backgammonFrames : List (List String)
backgammonFrames =
    [ [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KAKKKADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK"
      , "KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAKKKADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK"
      , "KAKKKADDDDDAAAAADDDDDAKKKADDDDDKCCCCCCCK"
      , "KKWWWKDDDDDAAAAADDDDDKZZZKDDDDDKCCCCCCCK"
      , "KKWWWKDDDDDAAAAADDDDDKZZZKDDDDDKCCCCCCCK"
      , "KKWWWKDDDDDAAAAADDDDDKZZZKDDDDDKCCCCCCCK"
      , "KCKKKCCDDDCCAAACCDDDCCKKKCCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KAKKKADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK"
      , "KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KKWWWKDDDDDKZZZKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAKKKADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCKKKCCKKKCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KAAAAADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCKKKCCKKKCKCCKKKCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCKKKCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWKKWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWKKWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWWWWWWWWWKCCKWWWWWWWWWKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK"
      , "KCCCCKWKKWWWWKKKCCKWWWWWWWKKKCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KAAAAADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDKWWWKDDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAKKKADDDDDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCKKKCCKKKCKCCKKKCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCKZZZKCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCKKKCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KAAAAADDDDDAKKKADKKKDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAKKKADKKKDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAAAAADDDDDKZZZKKWWWKKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCKKKCCKKKCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KAAAAADDDDDAKKKADKKKDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDKWWWKKZZZKKZZZKKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAKKKADKKKDAKKKADKKKDKCCCCCCCK"
      , "KAAAAADDDDDAAAAADKKKDAAAAADKKKDKCCCCCCCK"
      , "KAAAAADDDDDAAAAAKZZZKAAAAAKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAAAAAKZZZKAAAAAKWWWKKCCCCCCCK"
      , "KAAAAADDDDDAAAAAKZZZKAAAAAKWWWKKCCCCCCCK"
      , "KCAAACCDDDCCAAACCKKKCCAAACCKKKCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCAAACCDDDCCAAACCDDDCCAAACCDDDCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZWWZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZWWZZZKCCKZZZZWWZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZZZKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKZZZZZZZWWKCCKZZZZZZZZZKCCKCCCCCCCK"
      , "KCCCCKKKKKKKKKKKCCKKKKKKKKKKKCCKCCCCCCCK"
      , "KCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCKCCCCCCCK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    ]


chessFrames : List (List String)
chessFrames =
    [ [ "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "LTLTNLLNTLTTLLLNTLTTNLNNTLLTLNLN"
      , "LLLTLLLNLLLTNLNNLLLTLLLNLLLTLLLN"
      , "LLLTLNLNTLTTLLLNLLLTNLNNLTLTLLLN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NLNNTLTTNLNNTLTTNLNNTLTTNLNNTLTT"
      , "LLLNLLLTLLLNLLLTLLLNLLLTLLLNLLLT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TWTTNWNNTWTTNWNNTWTTNWNNTWTTNWNN"
      , "WWWTWWWNWWWTWWWNWWWTWWWNWWWTWWWN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "WNWNTWWTNWNNWWWTNWNNTWTTNWWNWTWT"
      , "WWWNWWWTWWWNTWTTWWWNWWWTWWWNWWWT"
      , "WWWNWTWTNWNNWWWTWWWNTWTTWNWNWWWT"
      ]
    , [ "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "LTLTNLLNTLTTLLLNTLTTNLNNTLLTLNLN"
      , "LLLTLLLNLLLTNLNNLLLTLLLNLLLTLLLN"
      , "LLLTLNLNTLTTLLLNLLLTNLNNLTLTLLLN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NLNNTLTTNLNNTLTTNLNNTLTTNLNNTLTT"
      , "LLLNLLLTLLLNLLLTLLLNLLLTLLLNLLLT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTWTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNWWWTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TWTTNWNNTWTTNWNNTTTTNWNNTWTTNWNN"
      , "WWWTWWWNWWWTWWWNTTTTWWWNWWWTWWWN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "WNWNTWWTNWNNWWWTNWNNTWTTNWWNWTWT"
      , "WWWNWWWTWWWNTWTTWWWNWWWTWWWNWWWT"
      , "WWWNWTWTNWNNWWWTWWWNTWTTWNWNWWWT"
      ]
    , [ "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "LTLTNLLNTLTTLLLNTLTTNLNNTLLTLNLN"
      , "LLLTLLLNLLLTNLNNLLLTLLLNLLLTLLLN"
      , "LLLTLNLNTLTTLLLNLLLTNLNNLTLTLLLN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NLNNTLTTNLNNTLTTNNNNTLTTNLNNTLTT"
      , "LLLNLLLTLLLNLLLTNNNNLLLTLLLNLLLT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNLNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTLLLNTTTTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTWTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNWWWTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TWTTNWNNTWTTNWNNTTTTNWNNTWTTNWNN"
      , "WWWTWWWNWWWTWWWNTTTTWWWNWWWTWWWN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "WNWNTWWTNWNNWWWTNWNNTWTTNWWNWTWT"
      , "WWWNWWWTWWWNTWTTWWWNWWWTWWWNWWWT"
      , "WWWNWTWTNWNNWWWTWWWNTWTTWNWNWWWT"
      ]
    , [ "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "LTLTNLLNTLTTLLLNTLTTNLNNTLLTLNLN"
      , "LLLTLLLNLLLTNLNNLLLTLLLNLLLTLLLN"
      , "LLLTLNLNTLTTLLLNLLLTNLNNLTLTLLLN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NLNNTLTTNLNNTLTTNNNNTLTTNLNNTLTT"
      , "LLLNLLLTLLLNLLLTNNNNLLLTLLLNLLLT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNLNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTLLLNTTTTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTWTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNWWWTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTWWTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNWWWTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNWTWTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TWTTNWNNTWTTNWNNTTTTNWNNTWTTNWNN"
      , "WWWTWWWNWWWTWWWNTTTTWWWNWWWTWWWN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "WNWNTWWTNWNNWWWTNWNNTWTTNNNNWTWT"
      , "WWWNWWWTWWWNTWTTWWWNWWWTNNNNWWWT"
      , "WWWNWTWTNWNNWWWTWWWNTWTTNNNNWWWT"
      ]
    , [ "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "LTLTNNNNTLTTLLLNTLTTNLNNTLLTLNLN"
      , "LLLTNNNNLLLTNLNNLLLTLLLNLLLTLLLN"
      , "LLLTNNNNTLTTLLLNLLLTNLNNLTLTLLLN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NLNNTLTTNLNNTLTTNNNNTLTTNLNNTLTT"
      , "LLLNLLLTLLLNLLLTNNNNLLLTLLLNLLLT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTLLTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNLLLTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNLTLTNNNNTTTTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNLNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTLLLNTTTTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTWTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNWWWTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTWWTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNWWWTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNWTWTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TWTTNWNNTWTTNWNNTTTTNWNNTWTTNWNN"
      , "WWWTWWWNWWWTWWWNTTTTWWWNWWWTWWWN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "WNWNTWWTNWNNWWWTNWNNTWTTNNNNWTWT"
      , "WWWNWWWTWWWNTWTTWWWNWWWTNNNNWWWT"
      , "WWWNWTWTNWNNWWWTWWWNTWTTNNNNWWWT"
      ]
    , [ "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "LTLTNNNNTLTTLLLNTLTTNLNNTLLTLNLN"
      , "LLLTNNNNLLLTNLNNLLLTLLLNLLLTLLLN"
      , "LLLTNNNNTLTTLLLNLLLTNLNNLTLTLLLN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NLNNTLTTNLNNTLTTNNNNTLTTNLNNTLTT"
      , "LLLNLLLTLLLNLLLTNNNNLLLTLLLNLLLT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTLLTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNLLLTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNLTLTNNNNTTTTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNLNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTLLLNTTTTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTWTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNWWWTNNNNTWTTNNNNTTTTNNNN"
      , "TTTTNNNNTWTTNNNNWWWTNNNNTTTTNNNN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNTWWTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNWWWTNNNNTTTT"
      , "NNNNTTTTNNNNTTTTNNNNWTWTNNNNTTTT"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TTTTNNNNTTTTNNNNTTTTNNNNTTTTNNNN"
      , "TWTTNWNNTWTTNWNNTTTTNWNNTWTTNWNN"
      , "WWWTWWWNWWWTWWWNTTTTWWWNWWWTWWWN"
      , "NNNNTTTTNNNNTTTTNNNNTTTTNNNNTTTT"
      , "WNWNTWWTNWNNWWWTNWNNTTTTNNNNWTWT"
      , "WWWNWWWTWWWNTWTTWWWNTTTTNNNNWWWT"
      , "WWWNWTWTNWNNWWWTWWWNTTTTNNNNWWWT"
      ]
    ]


goFrames : List (List String)
goFrames =
    [ [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNKKKNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXKKKXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNKKKNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK"
      , "KNNXXXXXXXXKKKWWWXXXXXXXXXXXNK"
      , "KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK"
      , "KNNXXXXXXXXKKKWWWXXXXXXXXXXXNK"
      , "KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK"
      , "KNNXXXXXXXXKKKWWWXXXXXXXXXXXNK"
      , "KNNXNNXNNXNKKKWWWNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXNNXNNXNKKKWWWKKKNXNNXNNXNK"
      , "KNNXXXXXXXXKKKWWWKKKXXXXXXXXNK"
      , "KNNXNNXNNXNKKKWWWKKKNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXNNXNNXNKKKWWWKKKNXNNXNNXNK"
      , "KNNXXXXXXXXKKKWWWKKKXXXXXXXXNK"
      , "KNNXNNXNNXNKKKWWWKKKNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXNNXNNXNKKKNXNKKKNXNNXNNXNK"
      , "KNNXXXXXXXXKKKXXXKKKXXXXXXXXNK"
      , "KNNXNNXNNXNKKKNXNKKKNXNNXNNXNK"
      , "KNNXNNXNNXNNXNKKKNXNWWWNXNNXNK"
      , "KNNXXXXXXXXXXXKKKXXXWWWXXXXXNK"
      , "KNNXNNXNNXNNXNKKKNXNWWWNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    , [ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNWWWNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXWWWXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNWWWNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXKKKXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNKKKNXNNXNNXNNXNK"
      , "KNNXNNXNNXNKKKNXNKKKNXNNXNNXNK"
      , "KNNXXXXXXXXKKKXXXKKKXXXXXXXXNK"
      , "KNNXNNXNNXNKKKNXNKKKNXNNXNNXNK"
      , "KNNXNNXNNXNNXNKKKNXNWWWNXNNXNK"
      , "KNNXXXXXXXXXXXKKKXXXWWWXXXXXNK"
      , "KNNXNNXNNXNNXNKKKNXNWWWNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXWWWXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNWWWNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXNNXNNXNNXNNXNNXNNXNNXNNXNK"
      , "KNNXXXXXXXXXXXXXXXXXXXXXXXXXNK"
      , "KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK"
      , "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      ]
    ]


defaultFrames : List (List String)
defaultFrames =
    [ [ "........................"
      , "....KKKKKK.............."
      , "...KWWWWWWK............."
      , "...KWKWWKWK...KKKKKK...."
      , "...KWWWWWWK..KSSSSSSK..."
      , "...KWWKKWWK..KSKSSKSK..."
      , "...KWWWWWWK..KSSSSSSK..."
      , "....KKKKKK...KSKSSKSK..."
      , ".............KSSSSSSK..."
      , "..............KKKKKK...."
      , "........................"
      , "......YYYYYYYYYY........"
      , "......YKKKKKKKKY........"
      , "......YYYYYYYYYY........"
      , "........................"
      , "........................"
      ]
    ]
